version = 0.1
[default.deploy.parameters]
stack_name = "dayflow-api"
resolve_s3 = true
s3_prefix = "dayflow-api"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
profile = "cloudsolarc"
parameter_overrides = "CognitoUserPoolId=\"us-east-1_3Gz6qj4Jk\" CognitoClientId=\"bf71fo0bs8sjisp1s600r0fph\" EventsTableName=\"schedules\" UsersTableName=\"users\" TasksTableName=\"tasks\" WeatherApiKey=\"f98fbc372d9968c0513a710a2e3e8272\" CorsOrigins=\"http://localhost:5173,http://localhost:3000,https://main.d37zspp7pemrc4.amplifyapp.com\" SesFromEmail=\"teamtwortt@gmail.com\" BriefingDispatcherEnabled=\"true\" BedrockGuardrailId=\"\" BedrockGuardrailVersion=\"DRAFT\" BedrockModelId=\"us.anthropic.claude-haiku-4-5-20251001-v1:0\""
image_repositories = []

[default.global.parameters]
region = "us-east-1"
